#! /bin/bash
# Copyright (c) 2023 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
# shellcheck source=collection-scripts/gather_utils
source "${SCRIPT_DIR}/gather_utils"

export PRODUCT="mce"
export MCE_NAME=""
export OPERATOR_NAMESPACE=""
export DEPLOYMENT_NAMESPACE=""
export HC_NAME=""
export HC_NAMESPACE="clusters" # default hosted cluster namespace
export IS_HUB=false

parse_args "$@"

pids=()

if check_if_engine; then
  IS_HUB=true
  log "Running MulticlusterEngine Must-Gather"
  "${SCRIPT_DIR}/gather_mce_logs" &
  pids+=($!)
fi

if check_if_spoke; then
  log "Running spoke cluster must-gather"
  "${SCRIPT_DIR}/gather_mce_spoke_logs" &
  pids+=($!)
fi

dump_hostedcluster &
pids+=($!)

# Check if PID array has any values, if so, wait for them to finish
if [ ${#pids[@]} -ne 0 ]; then
    log "All MCE must-gather scripts have started. Waiting on subprocesses to finish execution."
    wait "${pids[@]}"
    log "All MCE must-gather scripts have completed."
fi

log "MCE must-gather complete."
