#!/bin/bash
#set -x
# Copyright (c) 2021 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

echo -e "Running MultiClusterEngine (MCE) Must-Gather\n"
source mce-gather.sh

exit 0
